import { jsPDF } from 'jspdf';
import { Client } from '@/types/client';
import { mapGradeToScore, mapGradeToRiskLevel } from '@/lib/scoremapper';

export function exportClientReport(client: Client): void {
  /* =========================
     BACKEND DATA
  ========================= */
  const grade = client.credit_score ?? 'N/A';
  const score = mapGradeToScore(grade);
  const riskLevel = mapGradeToRiskLevel(grade);

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  /* =========================
     HEADER
  ========================= */
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('CreditScore AI', 20, 25);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Credit Assessment Report', pageWidth - 20, 25, { align: 'right' });

  doc.setTextColor(0, 0, 0);

  /* =========================
     CLIENT NAME
  ========================= */
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(
    `${client.prenom ?? ''} ${client.nom ?? 'Client'}`,
    20,
    55
  );

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(
    `Generated: ${new Date().toLocaleDateString()}`,
    20,
    62
  );

  /* =========================
     SCORE BOX
  ========================= */
  const gradeColors: Record<string, [number, number, number]> = {
    A: [34, 197, 94],
    B: [132, 204, 22],
    C: [250, 204, 21],
    D: [249, 115, 22],
    E: [239, 68, 68],
  };

  const [r, g, b] = gradeColors[grade] || [120, 120, 120];

  doc.setFillColor(r, g, b);
  doc.roundedRect(pageWidth - 60, 45, 40, 40, 5, 5, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text(grade, pageWidth - 40, 70, { align: 'center' });

  doc.setFontSize(10);
  doc.text(`Score: ${score}`, pageWidth - 40, 80, { align: 'center' });

  doc.setTextColor(0, 0, 0);

  /* =========================
     DIVIDER
  ========================= */
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 95, pageWidth - 20, 95);

  let yPos = 110;

  /* =========================
     PERSONAL INFO
  ========================= */
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Informations Personnelles', 20, yPos);
  yPos += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  [
    ['Age', client.age?.toString() ?? '—'],
    ['Credit Mix', client.credit_mix ?? '—'],
    ['Payment of Min Amount', client.payment_of_min_amount ?? '—'],
  ].forEach(([label, value]) => {
    doc.setTextColor(100, 100, 100);
    doc.text(label + ':', 20, yPos);
    doc.setTextColor(0, 0, 0);
    doc.text(value, 80, yPos);
    yPos += 7;
  });

  /* =========================
     CREDIT DETAILS
  ========================= */
  yPos += 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Credit Details', 20, yPos);
  yPos += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  [
    ['Outstanding Debt', `${client.outstanding_debt ?? 0}`],
    ['Credit Utilization (%)', `${client.credit_utilization_ratio ?? 0}`],
    ['Delayed Payments', `${client.num_of_delayed_payment ?? 0}`],
    ['Credit Inquiries', `${client.num_credit_inquiries ?? 0}`],
    ['Monthly EMI', `${client.total_emi_per_month ?? 0}`],
    ['Monthly Balance', `${client.monthly_balance ?? 0}`],
  ].forEach(([label, value]) => {
    doc.setTextColor(100, 100, 100);
    doc.text(label + ':', 20, yPos);
    doc.setTextColor(0, 0, 0);
    doc.text(value, 80, yPos);
    yPos += 7;
  });

  /* =========================
     RISK ASSESSMENT
  ========================= */
  yPos += 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Risk Assessment', 20, yPos);
  yPos += 10;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(r, g, b);
  doc.text(`Risk Level: ${riskLevel}`, 20, yPos);

  /* =========================
     FOOTER
  ========================= */
  doc.setFillColor(245, 245, 245);
  doc.rect(0, 270, pageWidth, 30, 'F');

  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(
    'Generated by CreditScore AI – For informational purposes only.',
    pageWidth / 2,
    280,
    { align: 'center' }
  );

  doc.save(
    `credit-report-${client.nom ?? 'client'}-${new Date()
      .toISOString()
      .split('T')[0]}.pdf`
  );
}
