"""Initial migration

Revision ID: 89638ccbbdb6
Revises: 7393868fcea5
Create Date: 2025-12-25 17:24:27.761807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89638ccbbdb6'
down_revision = '7393868fcea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
